-- =========================================================
-- THE EVERYTHING - SUPPORT REQUESTS
-- Run this ONCE in Supabase Dashboard -> SQL Editor -> New query
-- =========================================================

create table if not exists public.support_requests (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    username text not null,
    message text not null check (char_length(trim(message)) between 1 and 5000),
    status text not null default 'new' check (status in ('new', 'closed')),
    created_at timestamptz not null default now()
);

alter table public.support_requests enable row level security;

-- Only signed-in users may create a request, and only for their own account.
drop policy if exists "Authenticated users can create own support requests" on public.support_requests;
create policy "Authenticated users can create own support requests"
on public.support_requests
for insert
to authenticated
with check (auth.uid() = user_id);

-- No SELECT policy is intentionally created for normal site users.
-- You can read all requests safely from the Supabase Dashboard -> Table Editor.

create index if not exists support_requests_created_at_idx
on public.support_requests (created_at desc);

create index if not exists support_requests_user_id_idx
on public.support_requests (user_id);
